name: eclair-haskell
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/luc-tielen/eclair-haskell
license: BSD3
author: Luc Tielen
maintainer: luc.tielen@gmail.com
copyright: Luc Tielen, 2023
category: Bindings
extra-source-files:
  - README.md
  - cbits/eclair.c

dependencies:
  - base >= 4.7 && < 5
  - text == 2.*
  - bytestring == 0.12.*
  - vector >= 0.12.0 && < 1
  - array <= 1.0
  - containers == 0.*
  - mtl == 2.*
  - profunctors == 5.*

default-extensions:
  - OverloadedStrings
  - LambdaCase
  - TupleSections
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - DeriveGeneric
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - ScopedTypeVariables

ghc-options:
  - -Wall
  - -fhide-source-paths
  - -fno-show-valid-hole-fits
  - -fno-sort-valid-hole-fits

library:
  source-dirs: lib
  c-sources: cbits/*.c

tests:
  eclair-haskell-test:
    main: test.hs
    source-dirs: tests
    dependencies:
      - hspec >= 2.6.1 && < 3.0.0
      - hspec-hedgehog == 0.*
      - base >= 4.7 && < 5
      - template-haskell == 2.*
      - eclair-haskell
